[package]
name = "axmm"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS virtual memory management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axmm"
documentation = "https://arceos-org.github.io/arceos/axmm/index.html"

[features]
default = []
copy-from = ["page_table_multiarch/copy-from"]

[dependencies]
axhal = { workspace = true, features = ["paging"] }
axalloc = { workspace = true }
axconfig = { workspace = true }

log = "=0.4.21"
axerrno = "0.1"
lazyinit = "0.2"
memory_addr = "0.4"
kspin = "0.1"
memory_set = "0.4"
page_table_multiarch = { version = "0.5.5", optional = true }
