name: Build & Deploy docs

on: [push, pull_request]

env:
  rust-toolchain: nightly-2025-05-20

jobs:
  doc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: aarch64
      fail-fast: false
    permissions:
      contents: write
    env:
      default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust-toolchain }}
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: cargo-bin-cache
        cache-targets: false
    - uses: arceos-org/setup-musl@v1
      with:
        arch: ${{ matrix.arch }}
    - name: Build docs
      run: make doc_check_missing ARCH=${{ matrix.arch }}
    - name: Deploy to Github Pages
      if: ${{ github.ref == env.default-branch && matrix.os == 'ubuntu-latest' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        single-commit: true
        branch: gh-pages
        folder: target/doc
